#!/usr/bin/env python3

# Does naive conversion between sample format lengths by dropping or padding
# the least significant portion of the sample.

import argparse
import sys
import os

parser = argparse.ArgumentParser()
parser.add_argument("--in-bytes", type=int, default=2)
parser.add_argument("--out-bytes", type=int, default=2)
parser.add_argument("--out-channels", type=int, default=1)
args = parser.parse_args()

while True:
	insample = os.read(sys.stdin.fileno(), args.in_bytes)
	pad = bytes(b'\x00') * max(args.out_bytes - args.in_bytes, 0)
	outsample = pad + insample[-args.out_bytes:]

	os.write(sys.stdout.fileno(), outsample * args.out_channels)
